-- Carga inicial dos projetos que estavam publicados na home antes do CMS online.
-- Execute uma vez no SQL Editor do Supabase depois do schema.sql.

insert into public.projects (
  title,
  slug,
  category,
  project_type,
  project_status,
  status,
  is_featured,
  year,
  scope,
  concept,
  cover_image_url,
  gallery_images,
  youtube_videos,
  display_order
) values
(
  'Chacara AD.',
  'chacara-ad',
  'Residencial',
  'Area de lazer',
  'Concluido',
  'published',
  true,
  '2023',
  'Projeto residencial com foco em convivencia, lazer e integracao entre areas externas e internas.',
  'Espaco pensado para reunir familia e amigos, valorizando conforto, uso cotidiano e conexao com a area externa.',
  'assets/barra-page-12.jpg',
  '["assets/barra-page-12.jpg"]'::jsonb,
  '[]'::jsonb,
  10
),
(
  'Casa JG.',
  'casa-jg',
  'Residencial',
  'Casa e interiores',
  'Concluido',
  'published',
  true,
  '2024',
  'Projeto residencial com linguagem contemporanea, ambientes integrados e atencao aos detalhes de interiores.',
  'Residencia com proposta acolhedora, solucao funcional dos ambientes e unidade visual entre arquitetura e interiores.',
  'assets/barra-page-13.jpg',
  '["assets/barra-page-13.jpg"]'::jsonb,
  '[]'::jsonb,
  20
),
(
  'Casa JG. - Interiores',
  'casa-jg-interiores',
  'Residencial',
  'Interiores',
  'Concluido',
  'published',
  false,
  '2024',
  'Desenvolvimento de interiores com acabamentos, marcenaria e solucoes para conforto no cotidiano.',
  'Interiores criados para tornar a rotina mais pratica, confortavel e coerente com a identidade dos moradores.',
  'assets/barra-page-14.jpg',
  '["assets/barra-page-14.jpg"]'::jsonb,
  '[]'::jsonb,
  30
),
(
  'Apartamento JF. - Comercial',
  'apartamento-jf-comercial',
  'Comercial',
  'Restaurante',
  'Projeto / Conceito',
  'published',
  false,
  '2025',
  'Projeto de ambiente comercial voltado a experiencia, circulacao e identidade visual do espaco.',
  'Ambiente desenhado para equilibrar operacao, atmosfera e percepcao de marca.',
  'assets/barra-page-15.jpg',
  '["assets/barra-page-15.jpg"]'::jsonb,
  '[]'::jsonb,
  40
),
(
  'Apartamento JF.',
  'apartamento-jf',
  'Residencial',
  'Apartamento',
  'Concluido',
  'published',
  false,
  '2025',
  'Projeto de interiores para apartamento com aproveitamento inteligente do espaco e estetica acolhedora.',
  'Interiores planejados para ampliar a sensacao de conforto, organizar a rotina e valorizar cada ambiente.',
  'assets/barra-page-16.jpg',
  '["assets/barra-page-16.jpg"]'::jsonb,
  '[]'::jsonb,
  50
),
(
  'Rancho do Pastel',
  'rancho-do-pastel',
  'Restaurantes',
  'Comercial gastronomico',
  'Concluido',
  'published',
  true,
  '2025',
  'Ambiente gastronomico com presenca visual marcante, pensado para acolhimento, operacao e experiencia.',
  'Projeto comercial com identidade forte, circulacao clara e atmosfera convidativa para o publico.',
  'assets/barra-page-17.jpg',
  '["assets/barra-page-17.jpg"]'::jsonb,
  '[]'::jsonb,
  60
),
(
  'Samri Moda Fitness',
  'samri-moda-fitness',
  'Comercial',
  'Loja',
  'Concluido',
  'published',
  true,
  '2025',
  'Projeto comercial para varejo de moda fitness com identidade forte, exposicao de produtos e circulacao fluida.',
  'Loja pensada para destacar produtos, facilitar a jornada de compra e comunicar a personalidade da marca.',
  'assets/barra-page-18.jpg',
  '["assets/barra-page-18.jpg"]'::jsonb,
  '[]'::jsonb,
  70
)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  project_type = excluded.project_type,
  project_status = excluded.project_status,
  status = excluded.status,
  is_featured = excluded.is_featured,
  year = excluded.year,
  scope = excluded.scope,
  concept = excluded.concept,
  cover_image_url = excluded.cover_image_url,
  gallery_images = excluded.gallery_images,
  youtube_videos = excluded.youtube_videos,
  display_order = excluded.display_order,
  updated_at = now();
